# Adversarial end-review verdict

This review treats the uploaded bundle as the complete evidentiary record. The rubric has no PASS category, so the detailed returns below contain only claims receiving **WRONG**, **MISCITED**, or **UNCHECKED**. No claim is promoted by this review. 

## Final label disposition

| Result | Disposition                                                                                                                                     |
| ------ | ----------------------------------------------------------------------------------------------------------------------------------------------- |
| D1     | **PROVED unchanged**                                                                                                                            |
| L1     | **PROVED unchanged**                                                                                                                            |
| L2     | **PROVED unchanged**; its recorded placebo finding is misformulated, not a failure of L2                                                        |
| L3     | **PROVED under A($\tau$), unchanged**                                                                                                           |
| L4     | **PROVED as split in the card, unchanged**                                                                                                      |
| P1     | **DEMOTE: PROVED → CONJECTURE**                                                                                                                 |
| T1     | **PROVED at fixed policies, unchanged**; its chord check does not test the theorem under its actual hypotheses                                  |
| C1     | **PROVED certificate implication unchanged**; 18 pointwise numerical hits remain NUMERICAL, but they do not verify the full regional antecedent |

The **C1 three-way split is doing real epistemic work**. A conditional implication can be proved without proving that its antecedent holds anywhere; finite-node evidence can be numerical without being a region; and region certification requires additional continuity and supremum control. The defect is narrower: the phrase “certified nodes” is too strong when attached to the full C1 antecedent.

---

# 1. P1’s stated theorem is not established by its cited proof

## CLAIM

**WRONG — P1 is PROVED under A7′ in its on-path injective form, the stated round-2 action-set restriction, and the card’s objective.**

## HYPOTHESES

1. The P1 result row assumes **A7′ in its on-path injective form**.
2. P1 claims off-path beliefs obtained from full-support perturbations over plans.
3. P1’s proof perturbs every signal type toward every plan and uses injectivity over the full flagged plan–signal set to pin flagged off-path beliefs.
4. The round-2 action-set restriction says an available $Q^F$ is generated by a menu plan sharing the already-played pooled path and engagement status.
5. The blockholder objective contains the engagement cost $a_jC_j(s)$; the round-2 restriction does not require the alternative plan to have the same $C_j(s)$.
6. At $\kappa=0$ or $\kappa=1$, at least one of the three noise marks has zero primitive probability.

## PROOF

1. Hypothesis 1 identifies only selected, on-path flagged signals under a fixed cutoff policy.
2. Under Hypotheses 2–3, the perturbation assigns positive probability to plan–signal pairs that the cutoff policy does not select. The proof therefore needs the joint map
   [
   (j,s)\longmapsto(B_j^F,Q_j^F,a_j)
   ]
   to be injective over those pairs.
3. The bundle’s own 40-collision construction shows that on-path A7′ can hold while the joint map fails: the fixed policy never selects the colliding Voice histories, but a perturbation over plans does. Consequently, the proof’s off-path posterior is not pinned under the P1 row’s stated hypothesis.  
4. Hypothesis 4 also does not by itself establish sequential optimality. Suppose an alternative $Q^F$ raises the post-node payoff by $0.01$, but the plan used to represent that order has an engagement cost larger by $1$. Date-0 utility for the alternative plan is lower by $0.99$, even though the round-2 order is profitable after the existing plan’s engagement cost is sunk. The proof’s contradiction requires equality of the relevant costs, or a timing clause making the cost part of the round-2 choice. Neither is stated.
5. Hypothesis 5 exposes a second source mismatch: the card defines the objective with $-a_jC_j(s)$, whereas the cited P1 hypothesis and continuation display use $-C_j(s)$. The assertion that the proof displays the card’s definition “in full” is false as written.  
6. Under Hypothesis 6, the plan-only perturbation does not make every pooled history positive probability at $\kappa=0$ or $\kappa=1$. The proof would need a full-support perturbation of the noise law as well, followed by a limit back to the boundary.
7. Steps 2–6 are gaps in the cited construction of a PBE, not merely missing numerical evidence. P1’s current PROVED row must therefore move down.

## WHERE IT FAILS

1. **Off-path collision:** two order-inconsistent Voice plan–signal pairs produce the same flagged tuple. They cannot both be selected by one monotone cutoff policy, so on-path A7′ does not detect the collision; plan trembles do.
2. **Plan-dependent engagement costs:** two plans share the pooled path and engagement status but have different $C_j(s)$. Date-0 plan optimality then need not rule out a profitable flagged-order deviation.
3. **Noise-support boundary:** at $\kappa=0$, the two nonzero noise marks have zero probability; at $\kappa=1$, the zero noise mark has zero probability. Perturbing plans alone is not full support over pooled histories.

## LABEL CLAIMED

**CONJECTURE — demoted from PROVED.** A stronger theorem under joint flagged-tuple injectivity, continuation-equivalent costs, and a genuine full-support perturbation may be true, but that is not the theorem currently recorded.

## NUMERICAL CHECK REQUEST

Use the P1 signal grid and every plan in $\mathcal J$, not merely the equilibrium-selected plan.

1. Enumerate all flagged $(j,s)$ pairs and count duplicate values of $(B_j^F,Q_j^F,a_j)$.
   **Predicted under the needed joint hypothesis:** zero collisions; minimum pairwise tuple separation strictly positive.
   **Known boundary magnitude:** the pre-repair construction gives 40 collisions.
2. For every available alternative $Q_{j'}^F(s)$ sharing the pooled path, compare:

   * the actual round-2 gain while holding the current plan’s $C_j(s)$ fixed; and
   * $U_{j'}(s)-U_j(s)$.
     **Predicted under continuation equivalence:** discrepancy below $10^{-10}$.
     A discrepancy of order $\lvert C_{j'}(s)-C_j(s)\rvert$ identifies the missing cost condition.
3. At $\kappa\in{0,1}$, report the minimum probability assigned by the perturbation to every pooled history being priced.
   **Predicted for a genuine full-support perturbation:** strictly positive before taking the limit.
   **Predicted for the proof’s plan-only perturbation:** zero for at least some histories.

## NOTATION DELTA

None. Another menu element is denoted by another value of the card’s plan index $j$.

## NOT CLAIMED

That no PBE exists; that the pro-rata single-Voice menu fails joint injectivity after its global-strictness repair; that the inner pricing fixed point is nonunique under $m_0\ge0$; or that D1, L1, L2, L3, L4, T1, or C1 must be demoted with P1.

---

# 2. L2’s A($\tau$)-orientation placebo has the wrong predicted sign

## CLAIM

**WRONG — A($\tau$)’s maintained condition $C_h(\bar\pi)\le0$ predicts**
[
\partial_\kappa M_P\le0.
]

## HYPOTHESES

1. Under A($\tau$),
   [
   \partial_\kappa M_P
   ===================

   \Delta_m A'_\kappa C_h(\bar\pi).
   ]
2. $\Delta_m>0$.
3. A($\tau$) maintains $C_h(\bar\pi)\le0$.
4. The card requires $A'_\kappa$ to be bounded but imposes no sign on it.
5. The L2 placebo check requests a nonpositive derivative and records a hump-shaped $M_P$ as a failed A($\tau$)-orientation prediction.

## PROOF

1. Hypotheses 1–3 imply
   [
   \operatorname{sgn}(\partial_\kappa M_P)
   =======================================

   \operatorname{sgn}!\left(A'_\kappa C_h(\bar\pi)\right).
   ]
2. If $A'*\kappa>0$, Hypothesis 3 gives $\partial*\kappa M_P\le0$.
3. If $A'*\kappa<0$, Hypothesis 3 gives $\partial*\kappa M_P\ge0$.
4. If $A'_\kappa=0$, the derivative is zero regardless of the chord.
5. Hypothesis 4 permits all three cases. Therefore $C_h\le0$ alone does not imply the sign requested by the check.
6. The observed hump may show that a globally fixed orientation for the full enumerated pooled law fails, but it cannot be described as a contradiction of the chord sign alone. The core L2 invariance objects remain exactly constant in $\kappa$. 

## WHERE IT FAILS

1. **Negative coefficient:** L3’s Example A has $A'_\kappa=-1/4$. With $C_h<0$, the derivative is positive, the opposite of the placebo prediction.
2. **Zero coefficient:** locally constant weights give $A'_\kappa=0$ and zero motion even when $C_h<0$.
3. **Coefficient sign change:** $A'_\kappa$ can change sign over the $\kappa$ range while $C_h$ remains nonpositive, generating a hump without violating the chord orientation.

## LABEL CLAIMED

**L2 remains PROVED.** The failed claim is an ancillary pooled-cell placebo that is not part of L2’s flagged-cell invariance theorem. The committed L2 ranges and derivatives for the flagged posterior, $P^F$, entry probability, $M_F$, and $\Omega$ are all exactly $0.0$.

## NUMERICAL CHECK REQUEST

On $\kappa\in{0.05,0.10,\ldots,0.95}$:

1. Recover the A($\tau$) weights when the three-point representation is available.
2. Compute $A'*\kappa$ and compare the enumerated derivative with
   [
   \Delta_m A'*\kappa C_h(\bar\pi).
   ]
3. **Predicted sign:** the sign of $A'_\kappa C_h(\bar\pi)$; no unconditional sign.
4. **Predicted magnitude under A($\tau$):** identity residual below $10^{-10}$.
5. Report separately whether the support remains the same three points; a support failure and a sign-orientation failure are different findings.

## NOTATION DELTA

None.

## NOT CLAIMED

That the enumerated pooled law satisfies A($\tau$); that the hump is a numerical bug; that $M_P$ must be monotone; or that the L2 theorem extends to the pooled cell.

---

# 3. T1’s chord-magnitude check does not test A($\tau$) as stated

## CLAIM

**MISCITED — the $0.627946$ premium-percentage-point residual in `t2_t1_check.json` establishes that the enumerated two-round pooled law violates A($\tau$).**

## HYPOTHESES

1. A($\tau$) implies
   [
   \mathcal S_P
   ============

   \Delta_m\lvert A'_\kappa\rvert\lvert C_h(\bar\pi)\rvert
   ]
   using the **actual** weight derivative and actual upper support point.
2. The check substitutes $\lvert A'_\kappa\rvert=0.25$, taken from L3’s Example A.
3. The check substitutes the level-symmetric relation between the upper support point and the pooled engagement share.
4. Neither the value $0.25$ nor level symmetry is part of A($\tau$).
5. The check reports an implied $\lvert A'_\kappa\rvert$ between approximately $0.997$ and $1.158$.

## PROOF

1. Hypothesis 1 is an identity only after the actual representation weights and support are identified.
2. Hypotheses 2–4 show that the check replaces two unverified model objects with values from a particular witness economy.
3. A residual against those imposed values establishes that the witness calibration does not reproduce the enumerated sensitivity.
4. It does not separate:

   * failure of the three-point support condition;
   * failure of level symmetry;
   * a different but admissible $A'_\kappa$;
   * movement of the support with $\kappa$; or
   * movement of the kernel at fixed posterior.
5. Hypothesis 5 shows that changing only the coefficient from $0.25$ to the pointwise implied value would eliminate the displayed magnitude residual by construction. That does not prove A($\tau$), but it proves that the residual alone cannot refute it.
6. The numerical result stands; its citation as a direct test of A($\tau$)’s applicability is mismatched. 

## WHERE IT FAILS

1. **Different admissible coefficient:** a genuine three-point law may have $\lvert A'_\kappa\rvert=1.07$ rather than $0.25$.
2. **Non-level-symmetric weights:** the upper support point need not equal twice the pooled engagement share.
3. **Moving or four-point support:** in that case A($\tau$) does fail, but the failure must be demonstrated by enumerating the posterior support, not inferred from a formula evaluated with imposed inputs.

## LABEL CLAIMED

**T1 remains PROVED at fixed policies under its named hypotheses.** The check does not contradict the conditional theorem. A($\tau$)’s applicability to the actual two-round pooled cell remains **OPEN**, as the card already states.

## NUMERICAL CHECK REQUEST

At every $(\kappa,\tau,T)$ node:

1. Enumerate the complete pooled posterior law.
2. Record the number of distinct support points and the movement of each support point across adjacent $\kappa$ values.
   **Predicted under A($\tau$):** exactly three points ${0,\bar\pi/2,\bar\pi}$ and support movement below $10^{-12}$.
3. Recover $A_0,A_{1/2},A_1$ directly and finite-difference them.
   **Predicted under A($\tau$):**
   [
   A_0'=A_1'=A'*\kappa,\qquad A*{1/2}'=-2A'_\kappa,
   ]
   with residual below $10^{-10}$.
4. Recompute
   [
   \left|
   \mathcal S_P-\Delta_m\lvert A'_\kappa\rvert\lvert C_h(\bar\pi)\rvert
   \right|.
   ]
   **Predicted magnitude if the representation holds:** below $10^{-10}$, using the recovered coefficient rather than $0.25$.

## NOTATION DELTA

None.

## NOT CLAIMED

That A($\tau$) holds; that the existing $0.627946$ residual is small; that the check’s arithmetic is wrong; or that T1 gives an unconditional threshold result without A($\tau$) and A(br).

---

# 4. The O-1 experiment is not a window-margin refutation

## CLAIM

**WRONG — the O-1 ratios $1.06397$, $1.18373$, and $1.13631$ are values of $W_TC_T$ showing that window tightening raises pooled sensitivity.**

## HYPOTHESES

1. $W_T$ and $C_T$ compare two filing windows $T'<T$ in the two-round model at a common threshold.
2. The O-1 experiment compares a rule-on information regime with a rule-off regime.
3. The static O-1 model has no filing-window primitive.
4. T1’s own proof states that the O-1 ratios are not measurements of $W_TC_T$.
5. The card’s §9 nevertheless describes them as $W_TC_T$ and as a refutation of the window-margin analogue.

## PROOF

1. Hypothesis 1 requires two values of the card’s window $T$.
2. Hypotheses 2–3 provide no such pair.
3. Therefore the decomposition of the O-1 ratios may be written only as an analogous rule-on/rule-off weight-times-composition calculation; its factors are not $W_T$ and $C_T$.
4. Hypotheses 4–5 are directly contradictory. The proof’s description matches the experiment’s design; the card’s §9 description does not.
5. The O-1 result remains useful evidence that a composition factor can exceed one. It does not establish the sign of a comparison between, for example, $T=10$ and $T=5$.  

## WHERE IT FAILS

1. **No two window values:** a rule-on/rule-off comparison cannot identify the effect of changing $T$ while preserving the rule.
2. **Different information event:** turning disclosure off removes the partition; shortening $T$ retains the partition and changes filing dates, $B^F$, $Q^F$, and “no flag yet” histories.
3. **Different composition object:** the pooled histories left after a shorter window need not match the pooled histories in a no-rule regime.

## LABEL CLAIMED

**T1 remains PROVED at fixed policies.** The card’s §9 O-1 paragraph should be withdrawn or rewritten as an analogy. No unconditional window sign is supplied by the theorem or by O-1.

## NUMERICAL CHECK REQUEST

Run the actual two-round comparison at fixed policies for $T'=5$ and $T=10$, at each maintained threshold and $\kappa$ node:

[
W_T=\frac{1-\Omega(\tau,5)}{1-\Omega(\tau,10)},\qquad
C_T=\frac{\mathcal S_P(\kappa,\tau,5)}{\mathcal S_P(\kappa,\tau,10)}.
]

Report the direct ratio and verify

[
\frac{\mathcal S(\kappa,\tau,5)}
{\mathcal S(\kappa,\tau,10)}
============================

W_TC_T.
]

**Predicted sign:** $0\le W_T\le1$; $C_T$ and $W_TC_T-1$ are unsigned.
**Predicted magnitude:** identity residual below $10^{-10}$.
The count of nodes with $W_TC_T>1$ must be reported rather than forced to zero.

## NOTATION DELTA

None.

## NOT CLAIMED

That the O-1 ratios are wrong; that their boundary near $\Omega\approx0.343$ is wrong for that static experiment; or that genuine two-round window amplification cannot occur.

---

# 5. Existence at P1’s four failing numerical nodes remains unresolved

## CLAIM

**UNCHECKED — a cutoff PBE exists at each of the four numerical nodes where `t2_p1_check.json` did not meet its binding payoff criterion.**

## HYPOTHESES

1. The sweep used at most five seeds per grid node.
2. At four nodes the cutoff residual was approximately $10^{-11}$ or smaller.
3. At those same nodes the binding payoff residual remained between approximately $3.061\times10^{-4}$ and $1.488\times10^{-3}$.
4. The check’s requested equilibrium criterion requires both the cutoff and payoff conditions.
5. The sweep does not establish the full P1 hypotheses, including A3 and A6, at those nodes.

## PROOF

1. Hypotheses 2–4 show that a numerical fixed point of the cutoff update was found, but the associated plan assignment did not pass the best-response payoff test.
2. Therefore the four rows do not numerically certify a PBE.
3. Hypothesis 1 prevents the failed search from establishing nonexistence: the requested 30-seed search was not performed on those four grid nodes.
4. Hypothesis 5 also prevents using conditional P1 as an existence certificate for the calibration without first checking its antecedent.
5. The correct status is unresolved, not “no equilibrium” and not “numerically verified.”
6. The independent re-run confirms the four failures but also confirms that they are not $T=H$ corners and are not zero-pooled-share nodes. 

## WHERE IT FAILS

1. **Solver basin failure:** additional initial conditions may locate a payoff-consistent fixed point.
2. **Discontinuous best response:** a tiny cutoff residual may coexist with a nonzero payoff gap when the numerical cutoff map does not implement the exact best-response correspondence.
3. **Hypothesis failure:** the calibration may violate A3 or A6 at those nodes, in which case conditional P1 does not apply.

## LABEL CLAIMED

**No NUMERICAL existence label at these four nodes.** P1 is independently demoted to CONJECTURE for the proof-level defects in Finding 1; this numerical finding alone would justify only UNCHECKED at the four nodes.

## NUMERICAL CHECK REQUEST

Re-run exactly these four nodes:

* $\kappa=0.15,\ \tau=0.05,\ T=5$;
* $\kappa=0.15,\ \tau=0.075,\ T=1$;
* $\kappa=0.85,\ \tau=0.05,\ T=5$;
* $\kappa=0.85,\ \tau=0.075,\ T=1$.

Use all 30 requested seeds and report

[
\lVert k-\mathcal T(k;\vartheta)\rVert_\infty
]

together with the maximum profitable plan deviation.

**Predicted sign:** the maximum profitable deviation is nonnegative by construction.
**Predicted equilibrium magnitude:** cutoff residual below $10^{-10}$ and profitable-deviation magnitude below $10^{-9}$.
**Current observed deviation magnitudes:** $3.061\times10^{-4}$ to $1.488\times10^{-3}$.

## NOTATION DELTA

None.

## NOT CLAIMED

Nonexistence at the four nodes; convergence of a 30-seed run; that the four nodes are corners; or that their failure is caused by the pooled engagement share.

---

# 6. C1’s three-way split is honest, but “18 certified nodes” is over-cited

## CLAIM

**MISCITED — the 18 numerical nodes verify the full antecedent of the C1 certificate implication.**

## HYPOTHESES

1. The C1 implication requires AGE’s contraction and differentiability, a relatively open domain, an interior single equilibrium branch, twice continuous differentiability of $\Delta^{\mathrm{act}}$, a nonvanishing equilibrium liquidity derivative, and
   [
   g_r^{PE}>\mathcal B_r^{GE}.
   ]
2. The committed numerical criterion for a “certified” node is only
   [
   L_{\mathcal R}<1
   \quad\text{and}\quad
   \eta_r=g_r^{PE}-\mathcal B_r^{GE}>0.
   ]
3. The proof states that the run does not establish a modulus of continuity or a genuine supremum over a region.
4. The run uses finite-difference diagnostics for smoothness and branch behavior, but those diagnostics do not prove twice continuous differentiability or relative openness.
5. Every full $\kappa$ slice in the numerical record contains a sign change, so no entire displayed slice can be used as a C1 region.

## PROOF

1. Hypotheses 1–2 show that the numerical criterion verifies two important inequalities, not every component of the theorem’s antecedent.
2. Hypotheses 3–4 prevent promotion from pointwise calculations to a named open region.
3. Hypothesis 5 reinforces that a region cannot be inferred by taking an entire displayed slice.
4. The numerical claims themselves stand: 18 nodes have $L_{\mathcal R}<1$ and $\eta_r>0$, with the reported slack and contraction values.
5. The citation becomes inaccurate only when “certified nodes” is read as “the full C1 hypotheses are verified at those nodes.” The defensible description is **18 pointwise dominance-and-contraction nodes with supporting diagnostics**.
6. The implication/points/region split therefore remains epistemically substantive.   

## WHERE IT FAILS

1. **Branch boundary:** $L_{\mathcal R}<1$ and $\eta_r>0$ at a node do not rule out a nearby equilibrium-branch switch.
2. **Nondifferentiable policy point:** finite stencils can be stable at the selected width while the true map has a kink at a smaller scale.
3. **Outer boundary of $\Theta$:** checking ordered cutoffs does not by itself establish that the equilibrium lies in the full interior of $\Theta$.
4. **Between-node contraction failure:** pointwise values below one do not bound the supremum between nodes.

## LABEL CLAIMED

* **C1 certificate implication: PROVED unchanged.**
* **The 18 pointwise calculations: NUMERICAL unchanged**, but the object must be named narrowly.
* **A nonempty certified region: not claimed and not promoted.**

## NUMERICAL CHECK REQUEST

Around each of the 18 nodes, evaluate a neighborhood extending one-half of the existing grid spacing in each continuous coordinate.

Report:

[
\sup\lVert D_k\mathcal T\rVert
\quad\text{and}\quad
\inf\left(g_r^{PE}-\mathcal B_r^{GE}\right)
]

over that neighborhood, together with the minimum distance of $k$ from every boundary of $\Theta$ and a branch-continuity diagnostic.

**Predicted signs required for a regional promotion:**

[
\sup\lVert D_k\mathcal T\rVert<1,\qquad
\inf\eta_r>0.
]

Using the current minimum node slack $0.0595$, a conservative target would be a neighborhood lower bound above approximately $0.0298$. No such magnitude is established by the current grid.

## NOTATION DELTA

None.

## NOT CLAIMED

That the C1 split is cosmetic; that the implication borrows validity from the 18 nodes; that the 18 reported values are numerically wrong; or that a region cannot eventually be certified.

---

# 7. The card’s characterization of A7′ contains two false consequences

## CLAIM

**WRONG — for a menu, A7′ requires every $b_j^*$ to be strictly increasing, and injectivity forces $B^F$ itself to be continuum-valued.**

## HYPOTHESES

1. A7 concerns flagged histories and the observed tuple $(B^F,Q^F,a=1)$.
2. Exit and Hold do not flag in the core.
3. A7′ requires the composed terminal target of the selected flagged plan to be strictly increasing for every cutoff vector.
4. An injective map into the two-coordinate tuple need not have an injective first coordinate.
5. The pro-rata menu uses constant Hold and Exit terminal stakes while satisfying A7′ through its single Voice target.

## PROOF

1. By Hypotheses 1–2, passive plans carry no separation burden on the flagged set.
2. Hypotheses 3 and 5 provide a direct counterexample to the phrase “each $b_j^*$”: the qualifying pro-rata menu has non-strict passive terminal targets.
3. By Hypothesis 4, injectivity of
   [
   s\longmapsto(B^F,Q^F)
   ]
   forces the **tuple image** to be continuum-valued; it does not force either coordinate separately to be continuum-valued.
4. A card-conforming separation can have $B^F$ constant and $Q^F=b_j^*(s)-B^F$ strictly increasing. The sum still reveals $b_j^*(s)$ and the tuple remains injective.
5. The A7 attack itself identifies the same projection error: the cited cardinality argument applies to the tuple, not specifically to $B^F$.  
6. The correct primitive statement is narrower: strictness is required for flag-capable composed targets, with no backtracking across admissible Voice-plan switches; at least one coordinate of the tuple must carry the continuum.

## WHERE IT FAILS

1. **Passive plans:** Hold is constant and Exit weakly decreases, yet neither appears in the flagged tuple on the core domain.
2. **Constant filing stake:** $B^F$ can equal $\tau$ at every flagged signal while $Q^F$ separates signals.
3. **Multi-Voice backtracking:** even if every Voice target is strictly increasing within its own plan, overlapping ranges across a plan switch can violate composed-target strictness.

## LABEL CLAIMED

**No ledger label attaches to A7.** The standing hypothesis and its card wording require repair. L2 is not demoted because its proof uses the full flagged tuple and on-path recoverability. P1 is already demoted for its separate use of joint off-path injectivity.

## NUMERICAL CHECK REQUEST

Construct a flagged grid on which:

[
B^F=\tau,\qquad Q^F=b_j^*(s)-\tau,
]

with $b_j^*(s)$ pairwise distinct.

Report:

1. the range of $B^F$ — **predicted magnitude: exactly zero**;
2. the number of duplicate $(B^F,Q^F)$ tuples — **predicted: zero**;
3. the minimum tuple separation — **predicted: strictly positive**, of the same order as the grid spacing in $b_j^*$.

Separately enumerate every admissible Voice-plan switch and test for repeated terminal targets across the switch.

## NOTATION DELTA

None.

## NOT CLAIMED

That $B^F$ cannot be continuum-valued; that the pro-rata construction fails; that strict terminal-target separation is unnecessary for L2; or that within-plan strictness alone handles multi-Voice menus.

---

# 8. The model card is a mixed pre-C1/post-C1 snapshot

## CLAIM

**WRONG — the model card is a current post-ledger regeneration at commit `627642c`, with a consistent C1 status.**

## HYPOTHESES

1. The header identifies a 2026-08-21 post-ledger regeneration at commit `627642c` and says two-pass evidence closed on seven results.
2. The opening of §6 says all eight results now have two-pass evidence and that C1 moved on 2026-08-22.
3. The same §6 paragraph then says C1 is untouched and remains CONJECTURE.
4. The C1 result row labels the certificate implication PROVED.
5. The label ledger records a C1 move dated 2026-08-22 at commit `403ac8e`.

## PROOF

1. Hypotheses 2 and 3 assign mutually incompatible statuses to C1 in the same paragraph.
2. Hypotheses 1 and 5 identify different commits for the supposed current post-ledger state.
3. Hypotheses 3–5 mix the pre-ticket-29 and post-ticket-29 snapshots.
4. Because the card’s own header says a stale stamp is not accepted, this metadata state fails the card’s freshness rule.
5. The mathematical C1 implication can still be reviewed from its proof, but the card cannot truthfully describe itself as one internally consistent regenerated version. 

## WHERE IT FAILS

1. **Pre-C1 reading:** retain commit `627642c`, seven moved results, and C1 as CONJECTURE; remove the later C1 row and move.
2. **Post-C1 reading:** update the version stamp and commit to the post-ticket-29 state, remove “C1 is untouched,” and state eight closed results consistently.
3. **Date ordering:** a 2026-08-21 version cannot describe itself as regenerated after evidence recorded in its ledger as 2026-08-22 without an explicit later regeneration stamp.

## LABEL CLAIMED

**No mathematical result is demoted solely for this metadata error.** The model card itself must be regenerated. The theorem-label dispositions above are based on the individual statements, proofs, and numerical records in the bundle rather than on the contradictory status paragraph.

## NUMERICAL CHECK REQUEST

Run a card-consistency scan over the header, §6 introductory paragraph, C1 result row, and label ledger.

Encode PROVED as $1$ and CONJECTURE as $0$ for each occurrence of C1’s current status.

**Predicted magnitude for a consistent card:** maximum pairwise discrepancy $0$.
**Observed magnitude in this bundle:** $\lvert1-0\rvert=1$.
The scan should also report exactly one current commit; the bundle currently presents both `627642c` and `403ac8e` as operative states.

## NOTATION DELTA

None.

## NOT CLAIMED

That the C1 proof is invalid because of the stale stamp; that every earlier ledger move is false; or that the independent numerical re-run did not reproduce the committed JSON outputs.

---

## Bottom line

The theorem stack is materially stronger than its three raw FAIL flags make it appear. The L2 and T1 failures are principally **test-design or attribution failures**, and the four P1 numerical nodes establish neither existence nor nonexistence. The one result requiring a label demotion is **P1**, because its stated on-path A7′ hypothesis does not support its off-path belief construction, and its round-2 sequential-optimality argument lacks continuation equivalence for plan-dependent costs.

The corrected epistemic structure is:

[
\boxed{
\text{D1, L1, L2, L3, L4, T1, C1 implication retained;}
\quad
\text{P1 returned to CONJECTURE.}
}
]
